### New user sign-up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "test2",
    "email": "test2@company.com",
    "password": "deskflo123"
}

### User sign-in endpoint - authentication
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "test2@company.com",
    "password": "deskflo123"
}

### Get user profile endpoint - authorization
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGNvbXBhbnkuY29tIiwiaWF0IjoxNjU2MTMwNjE2LCJleHAiOjE2NTYxMzE4MTZ9.cr4vxZK_AulJQ7dJcEVUVIRy00v4QfOI-URkVAcvf_k