### New user sign-up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "test2",
    "email": "test2@company.com",
    "password": "deskflo123"
}

### User sign-in endpoint - authentication
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "test2@company.com",
    "password": "deskflo123"
}

### Get user profile endpoint - authorization
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGNvbXBhbnkuY29tIiwiaWF0IjoxNjU2MTk5OTYwLCJleHAiOjE2NTYyMDExNjB9.f9572___Qqp-SAD06QZCMbLJDaaGxdXdIB6_Gm5amQU

### Get new jwt
GET http://localhost:3001/v1/token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGNvbXBhbnkuY29tIiwiaWF0IjoxNjU2MTM3NDU3LCJleHAiOjE2NTczNDcwNTd9.BA1jTnrPJkeF6efgeJHcRThdIYYaweFyDWBrmGwuQsM

### User logout endpoint
DELETE http://localhost:3001/v1/user/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGNvbXBhbnkuY29tIiwiaWF0IjoxNjU2MzcxMDI5LCJleHAiOjE2NTYzNzIyMjl9.VXI9ykkZoPJWBbT56aofj2TFpmBl6j9Gipi8RFwI8Ls